# Generated by Django 4.1.2 on 2022-11-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_categories_categorie_rename_listings_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='seller_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(max_length=5000),
        ),
    ]
