# Generated by Django 4.1.2 on 2022-12-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='highest_bid_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
