# Generated by Django 4.1.2 on 2022-12-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_highest_bid_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.IntegerField()),
                ('listing_id', models.IntegerField()),
                ('text', models.CharField(max_length=5000)),
            ],
        ),
    ]
